export const env = {
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
  adminEmail: process.env.ADMIN_ORDER_EMAIL || "contact@comptoiralqods.ma",
  emailFrom: process.env.EMAIL_FROM || "Comptoir AlQods <onboarding@resend.dev>",
  resendApiKey: process.env.RESEND_API_KEY,
  adminPassword: process.env.ADMIN_PASSWORD || "change-me",
  supabaseUrl: process.env.SUPABASE_URL,
  supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY,
  supabaseStorageBucket: process.env.SUPABASE_STORAGE_BUCKET || "product-images",
  turnstileSiteKey: process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY,
  turnstileSecretKey: process.env.TURNSTILE_SECRET_KEY,
  smsProvider: process.env.SMS_PROVIDER || "demo",
  smsFrom: process.env.SMS_FROM || "ComptoirAlQods",
  twilioAccountSid: process.env.TWILIO_ACCOUNT_SID,
  twilioAuthToken: process.env.TWILIO_AUTH_TOKEN,
  twilioMessagingServiceSid: process.env.TWILIO_MESSAGING_SERVICE_SID,
  twilioFromNumber: process.env.TWILIO_FROM_NUMBER,
  paymentProvider: process.env.PAYMENT_PROVIDER || "demo",
  cmiMerchantId: process.env.CMI_MERCHANT_ID,
  cmiStoreKey: process.env.CMI_STORE_KEY,
  cmiGatewayUrl: process.env.CMI_GATEWAY_URL,
  payzoneMerchantId: process.env.PAYZONE_MERCHANT_ID,
  payzoneSecretKey: process.env.PAYZONE_SECRET_KEY,
  payzoneGatewayUrl: process.env.PAYZONE_GATEWAY_URL
};
